# Generated by Django 4.0.7 on 2022-09-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='distance',
            field=models.IntegerField(verbose_name='Время прохождения теста(мин)'),
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование вопроса')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecture.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='ask',
            field=models.ManyToManyField(to='lecture.ask', verbose_name='Вопросы'),
        ),
    ]
