# Generated by Django 4.0.7 on 2022-09-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_ask_ask_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='lecture.lecture', verbose_name='Лекция'),
            preserve_default=False,
        ),
    ]
