# Generated by Django 4.0.7 on 2022-09-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_remove_test_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='userClass',
        ),
        migrations.RemoveField(
            model_name='test',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='test',
            name='cat_subjects',
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
