# Generated by Django 4.0.7 on 2022-09-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='test',
            name='cat_subjects',
        ),
        migrations.RemoveField(
            model_name='test',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
