# Generated by Django 4.0.7 on 2022-09-24 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_remove_test_ask_remove_test_cat_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование вопроса')),
                ('mark', models.IntegerField(verbose_name='Балл')),
            ],
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование вопроса')),
                ('ask_true', models.BooleanField(verbose_name='Правильный вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(max_length=255, verbose_name='Наименование теста')),
                ('start_date', models.DateTimeField(verbose_name='Дата открытие теста')),
                ('end_date', models.DateTimeField(verbose_name='Дата закрытие теста')),
                ('distance', models.IntegerField(verbose_name='Время прохождения теста(мин)')),
                ('is_active', models.BooleanField(null=True, verbose_name='Опубликован')),
                ('answer', models.ManyToManyField(to='lecture.answer', verbose_name='Вопросы')),
                ('cat_subjects', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecture.subject', verbose_name='Предмет')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecture.lecture', verbose_name='Лекция')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='ask',
            field=models.ManyToManyField(to='lecture.ask', verbose_name='Список вопросов'),
        ),
    ]
