# Generated by Django 4.0.7 on 2022-09-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0009_answer_ask_test_answer_ask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='cat_subjects',
        ),
        migrations.RemoveField(
            model_name='test',
            name='topic',
        ),
        migrations.AddField(
            model_name='lecture',
            name='test',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.PROTECT, to='lecture.test', verbose_name='Наименование теста'),
        ),
    ]
