# Generated by Django 4.0.7 on 2022-09-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0011_alter_lecture_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
