# Generated by Django 4.0.7 on 2022-09-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0012_delete_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название темы')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('full_text', models.TextField(verbose_name='Контент')),
                ('cards', models.ImageField(upload_to='cards/%Y/%m/%d/', verbose_name='Карточки')),
                ('date', models.DateTimeField(verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(null=True, verbose_name='Опубликовано')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecture.subject', verbose_name='Предмет')),
                ('test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='lecture.test', verbose_name='Наименование теста')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'ordering': ['-date'],
            },
        ),
    ]
