# Generated by Django 4.0.7 on 2022-09-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0014_test_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_model',
            name='dictt',
        ),
    ]
