# Generated by Django 4.0.7 on 2022-09-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0015_remove_test_model_dictt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_model',
        ),
    ]
