# Generated by Django 4.0.7 on 2022-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0016_delete_test_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('dict', models.JSONField()),
            ],
        ),
    ]
