# Generated by Django 4.0.7 on 2022-09-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0017_test_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_model',
        ),
    ]
