# Generated by Django 4.0.7 on 2022-09-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0019_testresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['name'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='ask',
            options={'ordering': ['name'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['name_test'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['user'], 'verbose_name': 'Результаты тестов', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='lecture.test', verbose_name='Тест'),
        ),
    ]
