# Generated by Django 4.0.7 on 2022-09-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0022_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
