# Generated by Django 4.0.7 on 2022-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0023_delete_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100, verbose_name='Наименование теста')),
                ('user', models.CharField(max_length=155, verbose_name='Пользователь')),
                ('class_user', models.IntegerField(verbose_name='Класс')),
                ('date', models.CharField(max_length=50, verbose_name='Дата прохождения теста')),
                ('date_user', models.IntegerField(verbose_name='Время прохождения теста')),
                ('result_test', models.IntegerField(verbose_name='Количество баллов')),
            ],
            options={
                'verbose_name': 'Результаты тестов',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['user'],
            },
        ),
    ]
