# Generated by Django 4.0.7 on 2022-09-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0024_testresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
