# Generated by Django 4.0.7 on 2022-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0026_alter_testresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование вопроса'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование вопроса'),
        ),
    ]
