# Generated by Django 4.0.7 on 2022-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0027_alter_answer_name_alter_ask_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='attempts',
            field=models.IntegerField(default=3, max_length=10, verbose_name='Попытки'),
            preserve_default=False,
        ),
    ]
