# Generated by Django 4.0.7 on 2022-10-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0028_test_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='сhek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
