# Generated by Django 4.0.7 on 2022-10-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0030_timedate_delete_сhek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeDate',
        ),
    ]
