# Generated by Django 4.0.7 on 2022-11-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0031_delete_timedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='count_ask',
            field=models.IntegerField(default=1, verbose_name='Количество ответов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='count_answer',
            field=models.IntegerField(default=1, verbose_name='Количество вопросов'),
            preserve_default=False,
        ),
    ]
